extraction: 
  cpp:
      prepare:
        packages:
          - gcc-8
          - g++-8
          - libhdf5-dev
          - libeigen3-dev
          - python3.8-dev
          - python3.8-venv
      configure:
        command:
          - cd opencap; pwd; ls; mkdir build; cd build; CC=gcc-8 CXX=g++-8 cmake ../
      index:
        build_command:
          - pwd; ls; cd /opt/src/opencap/build; make -j2