language: generic

branches:
  only:
  - master
  
addons:
  apt:
    packages:
    - doxygen

matrix:
  include:
  - os: linux
    language: generic
    compiler: gcc
    dist: bionic
    addons:
      apt:
        update: true
        sources:
        - ubuntu-toolchain-r-test
        - deadsnakes
        packages:
        - gcc-8
        - g++-8
        - libhdf5-dev
        - libeigen3-dev
        - python3.8-dev
        - python3.8-venv
        - doxygen
        - python3.8
    env: CXX='g++-8' CC='gcc-8' BUILD_TYPE='release' PYTHON_VER=3.8
    
before_install:
- cd opencap; mkdir build
- cd build
- cmake ..
- sudo apt-get update
- sudo apt-get install python3 python3-pip python3-setuptools
- pip3 install --upgrade pip

install:
- make
- make test
- cd ../../
- pip3 install pytest
- pip3 install h5py
- pip3 install numpy
- pip3 install pyscf
- pip install .
- pytest

script:
- cd dox; doxygen Doxyfile.in; cd ..

after_success:
  - coveralls

deploy:
  provider: pages
  skip_cleanup: true
  local_dir: doxygen_docs
  github_token: $GH_REPO_TOKEN
  on:
    branch: master
    
