language: python
python:
  - 3.6
  - 3.7
  - 3.8

dist: bionic

# install your project and dependencies before building
CIBW_BEFORE_BUILD_LINUX: pip install cmake && yum install -y libhdf5-dev && yum install -y eigen3-devel

branches:
  only:
  - master
  
addons:
  apt:
    packages:
    - doxygen

before_install:
- ./.travis/before_install.sh
- pip3 install codecov

install:
- cd opencap; mkdir build
- cd build
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then CC=gcc-9 && CXX=g++-9  ; fi
- python --version
- cmake -DCODE_COVERAGE=ON -DPYTHON_EXECUTABLE=$(which python) -DCMAKE_BUILD_TYPE=RelWithDebInfo .. 
- cmake --build . --config Debug 
- ctest --output-on-failure
- cd ../../
- pip3 install pytest-cov
- pip3 install h5py
- pip3 install numpy
- pip3 install pyscf
- pip3 install .
- cd pyopencap
- py.test --cov-report=xml --cov=pyopencap tests

script:
  - cd ../opencap/build

after_success:
  # Create lcov report
  # capture coverage info
  - lcov   --directory . --capture --output-file coverage.info 
  # Remove everything not OpenCAP'
  - lcov --remove coverage.info '/usr/*' "${HOME}"'/.cache/*' --output-file coverage.info 
  - lcov --remove coverage.info '*eigen*' "${HOME}"'/.cache/*' --output-file coverage.info 
  - lcov --remove coverage.info '*_deps*' "${HOME}"'/.cache/*' --output-file coverage.info 
  - lcov --remove coverage.info '*tests*' "${HOME}"'/.cache/*' --output-file coverage.info 
  # output coverage data for debugging (optional)
  - lcov --list coverage.info
  # Uploading to CodeCov
  # '-f' specifies file(s) to use and disables manual coverage gathering and file search which has already been done above
  - bash <(curl -s https://codecov.io/bash) -f coverage.info || echo "Codecov did not collect coverage C++ reports"
  - cd ../../pyopencap
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml || echo "Codecov did not collect coverage Python reports"
  - cd ../../

stages:
  - name: deploy

jobs:
  include:
    # Deploy source distribution
    - stage: deploy
      name: Deploy source distribution
      install: skip
      script:
        - ls
        - python3 setup.py sdist --formats=gztar
    # deploy doxygen documentation
    - stage: deploy
      name: Build and deploy Dox documentation
      install: skip
      script:
        - cd dox; ls; doxygen Doxyfile.in; cd ..
      provider: pages
      skip_cleanup: true
      local_dir: doxygen_docs
      github_token: $GH_REPO_TOKEN
      on:
       branch: master
    # Deploy on linux
    - stage: deploy
      name: Build and deploy Linux wheels
      services: docker
      install: skip
      script: 
        - ls
        - python3 -m pip install cibuildwheel==1.5.5
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse
    # Deploy on mac
    - stage: deploy
      name: Build and deploy macOS wheels
      os: osx
      language: shell
      install: skip
      script: 
        - ls
        - CC=gcc-9
        - CXX=g++-9
        - python3 -m cibuildwheel --output-dir wheelhouse
        - ls wheelhouse