name: Build

on:
  push:
  pull_request:

jobs:
  build_linux_wheels:
    name: Build wheels on Linux
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: |
            yum install -y eigen3-devel python3-devel wget
            wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.gz
            tar zxvf hdf5-1.12.1.tar.gz
            cd hdf5-1.12.1
            ./configure --prefix=/opt/rh/devtoolset-10/root/usr/ --enable-cxx
            make
            make install
            cd ..

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build_macos_wheels:
    strategy:
      matrix:
        arch: [x86_64, arm64]
    name: Build macOS wheels for ${{ matrix.arch }}
    runs-on: ${{ matrix.arch == 'arm64' && 'macos-14' || 'macos-13' }}

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels with GCC
        uses: pypa/cibuildwheel@v2.16.5
        env:
          CIBW_ARCHS_MACOS: ${{ matrix.arch }}
          CIBW_BEFORE_ALL_MACOS: |
            brew install eigen gcc wget
            wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.gz
            tar zxvf hdf5-1.12.1.tar.gz
            cd hdf5-1.12.1
            ./configure --prefix=/usr/local/hdf5 --enable-cxx CC=gcc CXX=g++
            make
            sudo make install
            cd ..
          CIBW_ENVIRONMENT_MACOS: CC=gcc-13 CXX=g++-13 HDF5_ROOT=/usr/local/hdf5

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  make_sdist:
    name: Make sdist
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-serial-dev libeigen3-dev cmake

      - name: Build SDist
        run: pipx run build --sdist

      - uses: actions/upload-artifact@v4
        with:
          path: dist/*.tar.gz
