name: build-wheels

on: [push, pull_request]

jobs:
  build-wheels-linux:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_SKIP: "*-musllinux_*"
          CIBW_ARCHS_LINUX: x86_64
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y eigen3-devel &&
            yum install -y wget &&
            yum install -y hdf5 hdf5-devel &&
            yum install -y python3-devel
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  build-wheels-macos:
    name: Build wheels on macOS
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.23.2
        env:
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"
          CIBW_BEFORE_ALL_MACOS: >
            brew install eigen gcc hdf5
          CIBW_ENVIRONMENT_MACOS: CC=gcc-14 CXX=g++-14
          CIBW_BUILD: "cp39-* cp310-* cp311-* cp312-*"

      - name: Upload built wheels
        uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl
