name: build-wheels

on: [push, pull_request]

jobs:
  build-wheels-linux:
    name: Build wheels on Ubuntu
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["cp39", "cp310", "cp311", "cp312"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-serial-dev libeigen3-dev cmake gcc g++ patchelf

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_SKIP: "cp313-*"
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_ARCHS_LINUX: "x86_64"

  build-wheels-macos:
    name: Build wheels on macOS
    runs-on: ${{ matrix.macos }}
    strategy:
      matrix:
        macos: [macos-14]
        python-version: ["cp39", "cp310", "cp311", "cp312"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          brew install eigen hdf5 gcc@14

      - name: Install cibuildwheel
        run: python3 -m pip install cibuildwheel

      - name: Build wheels
        run: |
          python3 -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BUILD: "${{ matrix.python-version }}-*"
          CIBW_SKIP: "cp313-*"
          CIBW_ARCHS_MACOS: "x86_64 universal2"
          CC: gcc-14
          CXX: g++-14