name: macos

on: [push]

jobs:
  build-macos:
    name: Build and test with GCC on macOS ${{ matrix.macos }}
    runs-on: ${{ matrix.macos }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        macos: [macos-13, macos-14]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-activate-base: true
          activate-environment: true
          python-version: ${{ matrix.python-version }}
          miniforge-variant: Mambaforge
          use-mamba: true

      - name: Install system dependencies
        run: |
          brew install gcc eigen hdf5
          conda install -c conda-forge hdf5 eigen
          echo "System Info:"
          uname -a
          sysctl -n machdep.cpu.brand_string
          gcc --version || true
          which gcc-13 || which gcc-12 || which gcc-11 || which gcc

      - name: Build and test OpenCAP
        run: |
          export CC=$(which gcc-13 || which gcc-12 || which gcc-11 || which gcc)
          export CXX=$(which g++-13 || which g++-12 || which g++-11 || which g++)
          cd opencap
          mkdir -p build && cd build
          cmake -DCODE_COVERAGE=ON \
                -DHDF5_ROOT=$CONDA_PREFIX \
                -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
          make -j$(sysctl -n hw.logicalcpu)
          ctest --output-on-failure
          cd ../..

      - name: Build and test PyOpenCAP
        run: |
          export CC=$(which gcc-13 || which gcc-12 || which gcc-11 || which gcc)
          export CXX=$(which g++-13 || which g++-12 || which g++-11 || which g++)
          pip install . pytest pytest-cov codecov
          pip install h5py numpy pyscf numgrid pandas
          cd pyopencap
          pytest --cov=pyopencap --cov-report=xml
