name: macos

on: [push]

jobs:
  build-macos:
    name: Build and test with Clang on macOS ${{ matrix.macos }}
    runs-on: ${{ matrix.macos }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        macos: [macos-13, macos-14]
        python-version: ["3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: ${{ matrix.python-version }}
          auto-activate-base: false
          activate-environment: opencap-env
          environment-name: opencap-env
          miniconda-version: "latest" 

      - name: Install system dependencies
        run: |
          brew install eigen hdf5
          echo "System Info:"
          uname -a
          sysctl -n machdep.cpu.brand_string
          clang --version

      - name: Build and test OpenCAP
        run: |
          export CC=clang
          export CXX=clang++
          cd opencap
          mkdir -p build && cd build
          cmake -DCODE_COVERAGE=ON ..
          make -j$(sysctl -n hw.logicalcpu)
          ctest --output-on-failure
          cd ../..

      - name: Build and test PyOpenCAP
        run: |
          conda activate opencap-env
          export CC=clang
          export CXX=clang++
          pip install . pytest pytest-cov codecov
          pip install h5py numpy pyscf numgrid pandas
          cd pyopencap
          pytest --cov=pyopencap --cov-report=xml
