name: macos

on: [push]

jobs:
  build-macos:
    name: Build and test with GCC on macOS ${{ matrix.macos }}
    runs-on: ${{ matrix.macos }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        macos: [macos-13, macos-14]
        python-version: ["3.12"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install system dependencies
        run: |
          brew install eigen hdf5

      - name: Build and test OpenCAP
        run: |
          export CC=gcc-14
          export CXX=g++-14
          cd opencap
          mkdir -p build && cd build
          cmake -DCODE_COVERAGE=ON ..
          make -j$(sysctl -n hw.logicalcpu)
          ctest --output-on-failure
          cd ../..

      - name: Build and test PyOpenCAP
        run: |
          set -e
          export CC=gcc-14
          export CXX=g++-14
          pip install . pytest pytest-cov codecov
          pip install h5py numpy pyscf numgrid pandas
          cd pyopencap
          pytest --cov=pyopencap --cov-report=xml
